### GET request to /books result json with all books

GET http://localhost:3000/books

### GET request to /books/:id result is json object of that book with validation
GET http://localhost:3000/books/test
### result not a valid id as json response


### GET request to /books/:id with a valid id of 24 HEX digits but book for that ID is not in collection
GET http://localhost:3000/books/0000abcd0000abcd0000abcd

### GET requst to /books/:id with an valid id that exists in the collection books

GET http://localhost:3000/books/6abbc7d28515b235b5b12280

### POST request to /booksvalidate should contain title , author , pages and price
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "test Book",
  "author": "omar ",
  "price": 15,
  "pages": 255,
  "year": 2025,
  "genres": [
    "Programming",
    "Fantasy"
  ],
  "publisher": {
    "name": "me",
    "country": "SY"
  }
}


### DELETE request to an existing resourse, response book successfully deleted as json

DELETE  http://localhost:3000/books/6abce4489521c6800a68597c


### DELETE Request with valid id but not an existing resourse

DELETE  http://localhost:3000/books/0000abcd0000abcd0000abcd

### DELETE Request with not a valid id

DELETE  http://localhost:3000/books/test

### PUT request to update a resource completly
PUT  http://localhost:3000/books/6abcc90457bc9272e99c06d5
Content-Type: application/json

{
  "title":"test book 2",
  "author":  "test author",
  "price":123,
  "pages":1234

}


### PATCH requst to partially update a resource

PATCH http://localhost:3000/books/6abcc90457bc9272e99c06d5
Content-Type: application/json

{
  "title":"my title",
  "author":"my author"
}

#### PATCH with invalid properties in in the json
PATCH  http://localhost:3000/books/6abcc90457bc9272e99c06d5
Content-Type: application/json

{
  "title":"test 1 ",
  "author":"test 1 ",
  "foo": "test foo"
}


### You can also test the types of title , author , pages ,price and that the values of price and pages > 0


### test pagination
### GET first 2 books of page 1
GET http://localhost:3000/pagination?page=1&limi=2


### GET next 2 books of page 1

GET http://localhost:3000/pagination?page=2&limi=2

### GET next 2 books  of page 3
GET http://localhost:3000/pagination?page=3 &limi=2


### GET dafault page and default limit with no query parameter
GET http://localhost:3000/pagination
